# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/Admin/Library/Mobile Documents/com~apple~CloudDocs/Projects/Chess Engine"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/Admin/Library/Mobile Documents/com~apple~CloudDocs/Projects/Chess Engine"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/Admin/Library/Mobile Documents/com~apple~CloudDocs/Projects/Chess Engine/CMakeFiles" "/Users/Admin/Library/Mobile Documents/com~apple~CloudDocs/Projects/Chess Engine//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/Admin/Library/Mobile Documents/com~apple~CloudDocs/Projects/Chess Engine/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chess_ai

# Build rule for target.
chess_ai: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chess_ai
.PHONY : chess_ai

# fast build rule for target.
chess_ai/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_ai.dir/build.make CMakeFiles/chess_ai.dir/build
.PHONY : chess_ai/fast

chess_neural_network.o: chess_neural_network.cpp.o
.PHONY : chess_neural_network.o

# target to build an object file
chess_neural_network.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_ai.dir/build.make CMakeFiles/chess_ai.dir/chess_neural_network.cpp.o
.PHONY : chess_neural_network.cpp.o

chess_neural_network.i: chess_neural_network.cpp.i
.PHONY : chess_neural_network.i

# target to preprocess a source file
chess_neural_network.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_ai.dir/build.make CMakeFiles/chess_ai.dir/chess_neural_network.cpp.i
.PHONY : chess_neural_network.cpp.i

chess_neural_network.s: chess_neural_network.cpp.s
.PHONY : chess_neural_network.s

# target to generate assembly for a file
chess_neural_network.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_ai.dir/build.make CMakeFiles/chess_ai.dir/chess_neural_network.cpp.s
.PHONY : chess_neural_network.cpp.s

chess_position_encoding.o: chess_position_encoding.cpp.o
.PHONY : chess_position_encoding.o

# target to build an object file
chess_position_encoding.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_ai.dir/build.make CMakeFiles/chess_ai.dir/chess_position_encoding.cpp.o
.PHONY : chess_position_encoding.cpp.o

chess_position_encoding.i: chess_position_encoding.cpp.i
.PHONY : chess_position_encoding.i

# target to preprocess a source file
chess_position_encoding.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_ai.dir/build.make CMakeFiles/chess_ai.dir/chess_position_encoding.cpp.i
.PHONY : chess_position_encoding.cpp.i

chess_position_encoding.s: chess_position_encoding.cpp.s
.PHONY : chess_position_encoding.s

# target to generate assembly for a file
chess_position_encoding.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_ai.dir/build.make CMakeFiles/chess_ai.dir/chess_position_encoding.cpp.s
.PHONY : chess_position_encoding.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_ai.dir/build.make CMakeFiles/chess_ai.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_ai.dir/build.make CMakeFiles/chess_ai.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chess_ai.dir/build.make CMakeFiles/chess_ai.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chess_ai"
	@echo "... chess_neural_network.o"
	@echo "... chess_neural_network.i"
	@echo "... chess_neural_network.s"
	@echo "... chess_position_encoding.o"
	@echo "... chess_position_encoding.i"
	@echo "... chess_position_encoding.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

